DROP TABLE IF EXISTS endpoint_hit;
CREATE TABLE IF NOT EXISTS endpoint_hit(
    endpoint_hit_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    app_name VARCHAR(255),
    uri VARCHAR(255),
    client_ip_address VARCHAR(100),
    timestamp TIMESTAMP WITHOUT TIME ZONE
);