spring:
  mvc:
    format:
      date: "yyyy-MM-dd"
      time: "HH:mm:ss"
      date-time: "yyyy-MM-dd HH:mm:ss"
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true


stats-server:
  url: ${STATS_SERVER_URL}
